### ISSUE TITLE
ImportError: No module named pwd

### ISSUE THREAD

**Issue by stdavis** [tartley/rerun#11]
When I try to run rerun on my windows server 2012 machine (python version: 2.7.8) via Cmder I get the following error message:

```
(ugs) Z:\ugs-db\src (version2)
λ rerun "tox -e py27-develop"
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\Scripts\rerun-script.py", line 9, in <module>
    load_entry_point('rerun==1.0.23', 'console_scripts', 'rerun')()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pkg_resources\__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pkg_resources\__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    return self.resolve()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pkg_resources\__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\rerun\rerun.py", line 10, in <module>
    from .options import get_parser, parse_args, validate
  File "C:\Python27\ArcGIS10.3\lib\site-packages\rerun\options.py", line 4, in <module>
    import pwd
ImportError: No module named pwd
```

Any ideas?

**Comment by tartley** [comment]
Ahar, apologies - recent changes added the use of the stdlib 'pwd' module, but on checking the docs I now see that it isn't available on Windows.

I've made the code robust to failing to "import pwd", but I don't have a Windows machine to test it on. I pushed it out to PyPI: (v1.0.24)
https://pypi.python.org/pypi/rerun

If you could let me know whether it works, that would be great, thanks!

Without module 'pwd', you probably won't be able to use '--interactive or -I', but I suspect on Windows the distinction between a regular shell and an interactive shell doesn't exist, so you don't care.

EXCESSIVE DETAILS
The pwd module is used with "rerun -I or --interactive", which runs your command in an interactive shell (i.e. starts up a new instance of "bash --login" in which to run your given command.) However, some people don't use bash, so the command would behave differently in rerun (i.e. break) than when typed at their terminal. So, first rerun tries to get the type of shell it is being run from, using env var SHELL (sh like shells all set this, it's part of the POSIX standard), but if that isn't set (which I'm guessing it isn't on Windows cmd) then rerun falls back to asking the pwd module what type of login shell the user is configured to use.

**Comment by tartley** [comment]
v1.0.25 now updates the docs to reflect these changes.

**Comment by stdavis** [comment]
After updating to v1.0.25:
```
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.3\Scripts\rerun-script.py", line 9, in <module>
    load_entry_point('rerun==1.0.25', 'console_scripts', 'rerun')()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\rerun\rerun.py", line 141, in main
    signal.signal(signal.SIGTTOU, signal.SIG_IGN)
AttributeError: 'module' object has no attribute 'SIGTTOU'
```

Really appreciate you taking a look at this. I may have some time later today to also hack on it a bit. Not sure if I'll be much help or not.

**Comment by tartley** [comment]
riiiiiight, yep, I can see how that might happen. I don't really understand this, I coded it up by copying random posts of the internet (or someone advised me here on github, I forget) That crazy signal handling code is for when running a process in an interactive shell (i.e. using '-I' or '--interactive'.) That new shell we run grabs our terminal, meaning the rerun process loses access to the terminal. When that happens, rerun is sent this SIGTTOU signal to let us know that is happened, and in our signal handler we run something that grabs the terminal back for us to use again.

Presumably all of that code could be harmlessly skipped on Windows. I'll look at it later today with any luck... if you do get to open it up, leave a note here. Thanks!
